#!/usr/bin/python
import sys, json, bson, collections

for doc in bson.decode_file_iter(sys.stdin):
    if type(doc["_id"]) is bson.objectid.ObjectId:      # E_NO_JSON for that
        doc["_id"] = str(doc["_id"])
    try:
        print json.dumps(doc)
    except:
        print doc
        for (k,v) in doc.iteritems():
            print k, type(v)
        raise
